#!/bin/bash

service mysql start
mysqladmin -uroot password root

mysql -uroot -proot<<EOF
SET storage_engine=INNODB;
CREATE DATABASE IF NOT EXISTS gitlabhq_production DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, LOCK TABLES ON gitlabhq_production.* TO 'git'@'localhost';
UPDATE mysql.user SET password=PASSWORD('git') WHERE user='git';
\q
EOF


sed -i 's/secure password/git/g' /home/git/gitlab/config/database.yml
sudo -u git -H echo yes|bundle exec rake gitlab:setup RAILS_ENV=production

service redis-server  start

if [ -d /etc/tmpfiles.d ]; then
  echo 'd  /var/run/redis  0755  redis  redis  10d  -' | sudo tee -a /etc/tmpfiles.d/redis.conf
fi


sudo -u git -H bundle exec rake assets:precompile RAILS_ENV=production

service gitlab start
service nginx  start




sudo chmod -R ug+rwX,o-rwx /home/git/repositories/
sudo chmod -R ug-s /home/git/repositories/
find /home/git/repositories/ -type d -print0 | sudo xargs -0 chmod g+s

